### PR TITLE
Add permission context

### PR DESCRIPTION
**Pull request by Tobi406**
Adds a `permission=` context.

This only works for nodes the user has explicitly set and eg. not wildcard ones.

### CODE REVIEW

**Comment by lucko** [comment]
What's the use-case? I don't really think something like this is a good idea to be honest!

**Comment by Tobi406** [comment]
I sometimes (not very often too) see people asking on Discord for that.

A use case I can imagine is the following:

Two groups:
- `vip`
- `helper`

In the `helper` group there is a `test.permission permission=group.vip`, so to give a group a permission, but only if the player has the other group.

Cases found on Discord:
image
image

**Comment by lucko** [comment]
Hmm, honestly I think this is better implemented by just using groups properly. Including all permissions the player has set in their contexts feels really dirty.

**Comment by Tobi406** [comment]
Probably

**Comment by niqofdez** [comment]
Hi @Tobi406! You can provide a download link of the compiled plugin with this modification?

**Comment by Tobi406** [comment]
You can build it yourself, I haven't deleted the branch yet.

**Pull request closed without merging**
